"""init schema

Revision ID: 115a9c06ba4a
Revises: 
Create Date: 2026-07-18 19:18:34.387948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '115a9c06ba4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父部门 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='部门名称'),
    sa.Column('ldap_dn', sa.String(length=500), nullable=True, comment='LDAP DN'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graphiti_entities',
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='实体类型: document/concept/policy/product'),
    sa.Column('entity_ref_id', sa.UUID(), nullable=True, comment='关联的业务 ID（如文档 ID）'),
    sa.Column('name', sa.String(length=500), nullable=False, comment='实体名称'),
    sa.Column('current_version', sa.String(length=50), nullable=False, comment='当前版本'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False, comment='生效时间'),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True, comment='失效时间（NULL=当前有效）'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_facts',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='类别: preference/working/summary/entity'),
    sa.Column('fact_text', sa.Text(), nullable=False, comment='事实内容（自然语言）'),
    sa.Column('fact_key', sa.String(length=255), nullable=True, comment='结构化键（可选，用于精确查询）'),
    sa.Column('fact_value', sa.Text(), nullable=True, comment='结构化值（可选）'),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='向量嵌入（语义检索用）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否有效（软删除标记）'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间（NULL=永不过期）'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_facts_user_id'), 'memory_facts', ['user_id'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False, comment='租户名称'),
    sa.Column('domain', sa.String(length=255), nullable=True, comment='域名'),
    sa.Column('plan', sa.String(length=20), nullable=False, comment='套餐: free/pro/enterprise'),
    sa.Column('max_users', sa.Integer(), nullable=False, comment='最大用户数'),
    sa.Column('max_storage', sa.BigInteger(), nullable=False, comment='最大存储（字节）'),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='租户配置'),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True, comment='到期时间'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_configs',
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='租户 ID（私有部署可空）'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Agent 名称'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Agent 类型: qa/workflow/action'),
    sa.Column('description', sa.Text(), nullable=True, comment='Agent 描述'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Agent 专属配置（system_prompt/tools/model 等）'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='租户 ID（私有部署可空）'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='密钥名称（用户可读标识）'),
    sa.Column('key_hash', sa.String(length=128), nullable=False, comment='SHA-256 密钥哈希'),
    sa.Column('key_prefix', sa.String(length=20), nullable=False, comment='密钥前缀（明文前 8 位，用于识别）'),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=True, comment='授权范围列表'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间（空表示永不过期）'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='最后使用时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graphiti_events',
    sa.Column('entity_id', sa.UUID(), nullable=False, comment='实体 ID'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='事件类型: version_updated/status_changed/expired/deprecated/merged/split'),
    sa.Column('old_value', sa.Text(), nullable=True, comment='旧值'),
    sa.Column('new_value', sa.Text(), nullable=True, comment='新值'),
    sa.Column('event_source', sa.String(length=100), nullable=False, comment='事件来源'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False, comment='生效时间'),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True, comment='失效时间'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['graphiti_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_gaps',
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='租户 ID（SaaS 模式下隔离租户数据）'),
    sa.Column('topic', sa.String(length=500), nullable=False, comment='缺口主题（高频无结果查询词）'),
    sa.Column('search_count', sa.Integer(), nullable=False, comment='该主题的无结果搜索次数'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: high/medium/low（由搜索频率决定）'),
    sa.Column('description', sa.Text(), nullable=True, comment='缺口描述（自动生成或人工补充）'),
    sa.Column('suggestion', sa.Text(), nullable=True, comment='处理建议（人工填写）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: open/addressed'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='租户 ID'),
    sa.Column('plan', sa.String(length=20), nullable=False, comment='套餐: free/pro/enterprise'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='开始时间'),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True, comment='结束时间'),
    sa.Column('price', sa.Integer(), nullable=False, comment='价格（分）'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像 URL'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: admin/kb_admin/editor/viewer'),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='部门 ID'),
    sa.Column('clearance_level', sa.String(length=20), nullable=False, comment='密级: public/internal/confidential/secret'),
    sa.Column('manager_id', sa.UUID(), nullable=True, comment='上级 ID'),
    sa.Column('ldap_dn', sa.String(length=500), nullable=True, comment='LDAP DN'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_flows',
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='资源类型: document/kb/question'),
    sa.Column('resource_id', sa.UUID(), nullable=False, comment='资源 ID'),
    sa.Column('submitter_id', sa.UUID(), nullable=False, comment='提交者 ID'),
    sa.Column('reviewer_id', sa.UUID(), nullable=True, comment='审核者 ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/approved/rejected'),
    sa.Column('comment', sa.Text(), nullable=True, comment='审核意见'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: low/normal/high'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='对话标题'),
    sa.Column('agent_type', sa.String(length=50), nullable=False, comment='Agent 类型: qa/workflow/action'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_bases',
    sa.Column('name', sa.String(length=255), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='可见性: public/private/dept'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='所有者 ID'),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='部门 ID'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='标签列表'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_records',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='租户 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='使用的模型'),
    sa.Column('input_tokens', sa.Integer(), nullable=False, comment='输入 token'),
    sa.Column('output_tokens', sa.Integer(), nullable=False, comment='输出 token'),
    sa.Column('cost_cents', sa.Integer(), nullable=False, comment='成本（分）'),
    sa.Column('request_type', sa.String(length=30), nullable=False, comment='请求类型: chat/embed/rerank/vision'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('kb_id', sa.UUID(), nullable=False, comment='知识库 ID'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='标题'),
    sa.Column('content_html', sa.Text(), nullable=True, comment='HTML 内容'),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Tiptap JSON'),
    sa.Column('content_text', sa.Text(), nullable=True, comment='纯文本（检索用）'),
    sa.Column('doc_type', sa.String(length=20), nullable=False, comment='文档类型: md/html/docx/pdf'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: draft/pending_review/published/archived'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='所有者 ID'),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='部门 ID'),
    sa.Column('classification', sa.String(length=20), nullable=False, comment='密级: public/internal/confidential/secret'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='原始文件路径'),
    sa.Column('yjs_update', sa.LargeBinary(), nullable=True, comment='Yjs 二进制状态'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览次数'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI 自动摘要'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='AI 自动分类: 政策/SOP/技术文档/会议纪要/培训资料/产品文档/合同模板'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kb_members',
    sa.Column('kb_id', sa.UUID(), nullable=False, comment='知识库 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='知识库角色: admin/editor/viewer'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='对话 ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='引用来源'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='Token 消耗'),
    sa.Column('model_used', sa.String(length=100), nullable=True, comment='使用的模型'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_questions',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='提问者 ID'),
    sa.Column('kb_id', sa.UUID(), nullable=True, comment='关联知识库'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='问题标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='问题详情'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: open/answered/closed'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览数'),
    sa.Column('answer_count', sa.Integer(), nullable=False, comment='回答数'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签（逗号分隔）'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_actions',
    sa.Column('doc_id', sa.UUID(), nullable=False, comment='文档 ID'),
    sa.Column('assignee', sa.String(length=100), nullable=True, comment='负责人'),
    sa.Column('deadline', sa.Date(), nullable=True, comment='截止日期'),
    sa.Column('content', sa.Text(), nullable=False, comment='行动内容'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: high/medium/low'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/completed'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_comments',
    sa.Column('doc_id', sa.UUID(), nullable=False, comment='文档 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='评论者 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父评论 ID'),
    sa.Column('resolved', sa.Boolean(), nullable=False, comment='是否已解决'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['document_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('doc_id', sa.UUID(), nullable=False, comment='文档 ID'),
    sa.Column('content_html', sa.Text(), nullable=True, comment='HTML 快照'),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON 快照'),
    sa.Column('yjs_update', sa.LargeBinary(), nullable=True, comment='Yjs 二进制状态'),
    sa.Column('author_id', sa.UUID(), nullable=False, comment='操作者 ID'),
    sa.Column('summary', sa.String(length=255), nullable=True, comment='版本摘要'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='类型: bug/suggestion/praise/complaint'),
    sa.Column('content', sa.Text(), nullable=False, comment='反馈内容'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: open/processing/resolved/closed'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: low/normal/high/urgent'),
    sa.Column('related_message_id', sa.UUID(), nullable=True, comment='关联消息 ID'),
    sa.Column('response', sa.Text(), nullable=True, comment='处理回复'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['related_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='接收用户 ID'),
    sa.Column('notification_type', sa.String(length=30), nullable=False, comment='通知类型: personal_digest/document_change/gap_alert'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='通知内容'),
    sa.Column('doc_id', sa.UUID(), nullable=True, comment='关联文档 ID'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('read_at', sa.String(length=30), nullable=True, comment='已读时间 ISO 格式'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_answers',
    sa.Column('question_id', sa.UUID(), nullable=False, comment='问题 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='回答者 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='回答内容'),
    sa.Column('is_accepted', sa.Boolean(), nullable=False, comment='是否被采纳'),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False, comment='是否 AI 生成'),
    sa.Column('vote_count', sa.Integer(), nullable=False, comment='投票数'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['qa_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_logs',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='用户 ID（匿名搜索时为空）'),
    sa.Column('query', sa.Text(), nullable=False, comment='搜索关键词'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='搜索源: knowledge_base/oa/erp/crm'),
    sa.Column('result_count', sa.Integer(), nullable=False, comment='返回结果数'),
    sa.Column('clicked', sa.Boolean(), nullable=False, comment='是否点击了结果'),
    sa.Column('clicked_doc_id', sa.UUID(), nullable=True, comment='点击的文档 ID'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clicked_doc_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_logs')
    op.drop_table('qa_answers')
    op.drop_table('notifications')
    op.drop_table('feedbacks')
    op.drop_table('document_versions')
    op.drop_table('document_comments')
    op.drop_table('document_actions')
    op.drop_table('qa_questions')
    op.drop_table('messages')
    op.drop_table('kb_members')
    op.drop_table('documents')
    op.drop_table('usage_records')
    op.drop_table('knowledge_bases')
    op.drop_table('conversations')
    op.drop_table('audit_flows')
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_table('knowledge_gaps')
    op.drop_table('graphiti_events')
    op.drop_table('api_keys')
    op.drop_table('agent_configs')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_memory_facts_user_id'), table_name='memory_facts')
    op.drop_table('memory_facts')
    op.drop_table('graphiti_entities')
    op.drop_table('departments')
    # ### end Alembic commands ###
